# core/constants/__init__.py

from core.constants.choices import (
    PRODUCT_STATUS_CHOICES,
    ARTWORK_TYPE_CHOICES,
    EXHIBITION_STATUS_CHOICES,
    ORDER_STATUS_CHOICES,
    PAYMENT_METHOD_CHOICES,
    ARTIST_LEVEL_CHOICES,
)

from core.constants.error_codes import (
    ERROR_GENERAL,
    ERROR_NOT_FOUND,
    ERROR_UNAUTHORIZED,
    ERROR_PAYMENT_FAILED,
)

from core.constants.settings import (
    MAX_ARTWORK_SIZE,
    MAX_ARTWORKS_PER_ARTIST,
    MAX_FEATURED_ARTWORKS,
    DEFAULT_COMMISSION_RATE,
    MIN_WITHDRAWAL_AMOUNT,
)

__all__ = [
    # Choices
    'PRODUCT_STATUS_CHOICES',
    'ARTWORK_TYPE_CHOICES',
    'EXHIBITION_STATUS_CHOICES',
    'ORDER_STATUS_CHOICES',
    'PAYMENT_METHOD_CHOICES',
    'ARTIST_LEVEL_CHOICES',

    # Error codes
    'ERROR_GENERAL',
    'ERROR_NOT_FOUND',
    'ERROR_UNAUTHORIZED',
    'ERROR_PAYMENT_FAILED',

    # Settings
    'MAX_ARTWORK_SIZE',
    'MAX_ARTWORKS_PER_ARTIST',
    'MAX_FEATURED_ARTWORKS',
    'DEFAULT_COMMISSION_RATE',
    'MIN_WITHDRAWAL_AMOUNT',
]